# Generated by Django 4.2.7 on 2024-02-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bugger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="staic/media")),
                ("cusine", models.CharField(max_length=200)),
                ("rating", models.CharField(max_length=200)),
                ("flavor", models.CharField(max_length=200)),
            ],
        ),
    ]
