# Generated by Django 4.2.7 on 2024-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank="True", max_length=200, null=True, verbose_name="addredss"
            ),
        ),
    ]
