# Generated by Django 4.2.7 on 2023-11-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostHashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("date_time", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField()),
                (
                    "hashtags",
                    models.ManyToManyField(
                        blank=True, related_name="blog_posts", to="blog.posthashtag"
                    ),
                ),
            ],
        ),
    ]
