# Generated by Django 4.2.7 on 2023-11-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=200)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="blog.blog"
                    ),
                ),
            ],
        ),
    ]
