# Generated by Django 4.2.7 on 2023-11-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_share_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="share_blog",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="Blog_Commnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=200)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="blog.blog"
                    ),
                ),
            ],
        ),
    ]
