# Generated by Django 4.2.7 on 2023-11-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blog_commnet_date_time_share_blog_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog_commnet",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
