# Generated by Django 4.2.7 on 2023-12-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blog_commnet_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstaPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
